/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b084ba59-d9ad-4e76-bfd4-b4dc3caada2d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_LSdBrvicF",
    "aws_user_pools_web_client_id": "39mf8bs7e4phps9gc9lf2o5925",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://6sxsn2i2cve6hmistytpubcz2y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-b774zv3a7vcujenpgtroynwp4i"
};


export default awsmobile;
